# Generated by Django 6.0.6 on 2026-07-27 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('context_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_queries',
                'indexes': [models.Index(fields=['user', '-created_at'], name='assistant_q_user_id_9933d5_idx')],
            },
        ),
    ]
