# Generated by Django 6.0.6 on 2026-07-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        ('loans', '0003_loanapplication_credit_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantquery',
            name='language',
            field=models.CharField(default='ur', max_length=5),
        ),
        migrations.AddField(
            model_name='assistantquery',
            name='related_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_queries', to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='assistantquery',
            name='role_at_time',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
