# Generated by Django 6.0.6 on 2026-07-29 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_preferred_language'),
        ('assistant', '0002_assistantquery_language_assistantquery_related_loan_and_more'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('narrative', models.TextField(blank=True)),
                ('language', models.CharField(default='ur', max_length=7)),
                ('context_snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=10)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_summaries', to='accounts.farmerprofile')),
                ('settlement_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='season_summary', to='settlements.settlementinvoice')),
            ],
            options={
                'db_table': 'season_summaries',
            },
        ),
    ]
