"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured 

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = os.environ.get("DEBUG", "True") == "True"
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")
ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if host]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'apps.accounts',
    'apps.land',
    'apps.contracts',
    'apps.crops',
    'apps.delivery',
    'apps.escrow',
    'apps.inputs',
    'apps.insurance',
    'apps.loans',
    'apps.settlements',
    'apps.wallets',
    'apps.notifications',
    'apps.community',
    'apps.credit',
    'apps.assistant',
    'django_celery_beat',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
    'drf_spectacular', 
]

NUMBERDAR_APPROVAL_TIMEOUT_DAYS = int(os.environ.get('NUMBERDAR_APPROVAL_TIMEOUT_DAYS', 7))
PARTNER_BANK_API_URL = os.environ.get('PARTNER_BANK_API_URL', 'MOCK')
PARTNER_BANK_API_KEY = os.environ.get('PARTNER_BANK_API_KEY', '')
PARTNER_BANK_PLATFORM_ID = os.environ.get('PARTNER_BANK_PLATFORM_ID', 'HAL_MVP_23')
USE_MOCK_AI = os.getenv('USE_MOCK_AI', 'false').lower() == 'true'

ADMIN_URL_PATH = os.environ.get('DJANGO_ADMIN_URL', 'admin/') 
ADMIN_IP_ALLOWLIST = [ip.strip() for ip in os.environ.get('DJANGO_ADMIN_IP_ALLOWLIST', '').split(',') if ip.strip()]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shared.middleware.request_id.RequestIDMiddleware',  
    'shared.middleware.audit_log.AuditLogMiddleware',
    'shared.middleware.admin_ip_allowlist.AdminIPAllowlistMiddleware',
]

LOGIN_URL = 'two_factor:login'

LOGGING = {
  'version': 1,
  'disable_existing_loggers': False,
  'formatters': {'audit': {'format': '%(asctime)s %(message)s'}},
  'handlers': {'console': {'class': 'logging.StreamHandler', 'formatter': 'audit'}},
  'loggers': {'hal.audit': {'handlers': ['console'], 'level': 'INFO', 'propagate': False}},
}

SECURE_REFERRER_POLICY = 'same-origin' 
SESSION_COOKIE_SECURE = not DEBUG 
CSRF_COOKIE_SECURE = not DEBUG 

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

ROOT_URLCONF = 'config.urls'
AUTH_USER_MODEL = 'accounts.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'fasal_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            'options': '-c lock_timeout=3000 -c statement_timeout=10000'
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'EXCEPTION_HANDLER': 'shared.exceptions.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'shared.pagination.StandardResultsPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': ['rest_framework.throttling.ScopedRateThrottle'],
    'DEFAULT_THROTTLE_RATES': {'credit_check': '5/hour', 'numberdar_action': '30/min', 'otp_verify': '10/hour', 'ai_assistant': '20/hour', 'login': '10/hour', 'password_reset': '5/hour',}, 
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Hal API',
    'DESCRIPTION': "Digital escrow platform connecting farmers, banks, shopkeepers, and factory buyers.",
    'VERSION': '1.0.0',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=24),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'  

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'          
EMAIL_HOST = 'smtp.gmail.com'                                  
EMAIL_PORT = 587                                 
EMAIL_USE_TLS = True                                              
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')                      
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')                
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

CORS_ALLOW_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')
CORS_ALLOW_CREDENTIALS = True

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'poc-dev-secret-key-change-in-prod')
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')

if not DEBUG and SECRET_KEY == 'poc-dev-secret-key-change-in-prod': 
  raise ImproperlyConfigured(
    "DJANGO_SECRET_KEY must be set to a real, unique secret when DEBUG=False. "
    "Refusing to start with the development placeholder key.")

if not DEBUG and ALLOWED_HOSTS == ['*']: 
  raise ImproperlyConfigured(
    "DJANGO_ALLOWED_HOSTS must list your real domain(s) when DEBUG=False. "
    "Refusing to start with a wildcard host allowlist.")

if not DEBUG:  
  SECURE_SSL_REDIRECT = True
  SECURE_HSTS_SECONDS = 31536000
  SECURE_HSTS_INCLUDE_SUBDOMAINS = True
  SECURE_HSTS_PRELOAD = True
  SECURE_CONTENT_TYPE_NOSNIFF = True
  
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY')  
CNIC_INDEX_KEY = os.environ.get('CNIC_INDEX_KEY')  

if not DEBUG and (not FIELD_ENCRYPTION_KEY or not CNIC_INDEX_KEY): 
  raise ImproperlyConfigured("FIELD_ENCRYPTION_KEY and CNIC_INDEX_KEY must both be set when DEBUG=False.")