# Generated by Django 6.0.6 on 2026-07-31 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateVerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('secp_certificate', 'SECP Certificate'), ('incorporaion_certificate', 'Incorporation Certificate')], max_length=35)),
                ('file', models.FileField(upload_to='corporate_verification/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corporate_verification_documents',
                'unique_together': {('user', 'document_type')},
            },
        ),
    ]
