# Generated by Django 6.0.6 on 2026-08-01 20:02

import shared.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_corporateverificationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnic_index',
            field=models.CharField(db_index=True, editable=False, max_length=68, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=shared.encrypted_fields.EncryptedCharField(max_length=500),
        ),
    ]
